export * from './iForm.service';
import { IFormService } from './iForm.service';
export * from './iModule.service';
import { IModuleService } from './iModule.service';
export * from './iOrganization.service';
import { IOrganizationService } from './iOrganization.service';
export * from './iPost.service';
import { IPostService } from './iPost.service';
export * from './iResource.service';
import { IResourceService } from './iResource.service';
export * from './iRole.service';
import { IRoleService } from './iRole.service';
export * from './iTest.service';
import { ITestService } from './iTest.service';
export * from './iUser.service';
import { IUserService } from './iUser.service';
export const APIS = [IFormService, IModuleService, IOrganizationService, IPostService, IResourceService, IRoleService, ITestService, IUserService];
